Refactor/1069 duplication in handlers
GIScience/openrouteservice pull request #1075
Opened 2021-10-14 12:27 UTC by koebi

### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [x] ~3. I have documented my code using JDocs tags.~
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] ~6. I have created API tests for any new functionality exposed to the API.~
- [x] ~7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).~
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [x] ~10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).~
- [x] ~11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.~
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [x] ~13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].~

Fixes #1067

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

2021-10-18 08:30 UTC, sfendrich requested changes

2021-10-18 08:30 UTC, sfendrich commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/centrality/CentralityRequestHandler.java
>      public CentralityRequestHandler() {
As the constructor only calls super, it can be omitted completely.

2021-10-18 08:30 UTC, sfendrich commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +    public int convertMetrics(MatrixRequestEnums.Metrics[] metrics) throws ParameterValueException {
I think there is a bigger design problem here (and in the following methods) . Just removing the `static` keyword does not remove the issue that the methods are somewhat unrelated to the object. Therefore, I would prefer to either (1) cleanup completely or (2) keep the methods static to make the issue easier to find later.

2021-10-18 08:30 UTC, sfendrich commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +        for (Field f: MatrixErrorCodes.class.getFields()) {
Please add a comment `// TODO: cleanup usage of reflection`

2021-10-18 08:30 UTC, sfendrich commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestHandler.java
> +        for (Field f: RoutingErrorCodes.class.getFields()) {
Please add a comment `// TODO: cleanup usage of reflection`

2021-10-18 08:30 UTC, sfendrich commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +            params.setAvoidAreas(avoidAreas);
Can we avoid the duplication of this code in `RouteRequestHandler` lines 243ff?

2021-10-18 08:30 UTC, sfendrich commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestHandler.java
> +        if (options.hasAvoidPolygonFeatures()) {
See duplication comment in `MatrixRequestHandler`

2021-10-18 09:17 UTC, koebi commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +    public int convertMetrics(MatrixRequestEnums.Metrics[] metrics) throws ParameterValueException {
I'd prefer (1), any recommendations on how to handle this?

2021-10-18 12:24 UTC, sfendrich commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +    public int convertMetrics(MatrixRequestEnums.Metrics[] metrics) throws ParameterValueException {
Not without a deeper analysis. We would need to find a good "home"-class for these methods.

2021-10-27 13:33 UTC, koebi commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +            params.setAvoidAreas(avoidAreas);
done

2021-10-27 13:33 UTC, koebi commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestHandler.java
> +        if (options.hasAvoidPolygonFeatures()) {
done

2021-10-27 13:33 UTC, koebi commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestHandler.java
> +        for (Field f: RoutingErrorCodes.class.getFields()) {
done

2021-10-27 13:33 UTC, koebi commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +        for (Field f: MatrixErrorCodes.class.getFields()) {
done

2021-10-27 13:33 UTC, koebi commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java
> +    public int convertMetrics(MatrixRequestEnums.Metrics[] metrics) throws ParameterValueException {
Will be addressed as outlined in #1067

2021-10-27 13:33 UTC, koebi commented on openrouteservice/src/main/java/org/heigit/ors/api/requests/centrality/CentralityRequestHandler.java
>      public CentralityRequestHandler() {
done

2021-10-27 15:25 UTC, sfendrich approved these changes
LGTM

2021-10-28 11:41 UTC, merged