Add languages: Romanian, Esperanto
GIScience/openrouteservice pull request #1206
Opened 2022-08-19 12:14 UTC by takb

Adds languages Romanian and Esperanto, fixes JSON formatting in language resource files

2022-08-22 11:29 UTC, koebi requested changes
Looks good so far. I really don't like the german translation, but can live with it - the two issues mentioned should be fixed, though.
As stated, I'm a bit confused by the esperanto translation, but have no experience with the language whatsoever, I'd assume we could merge anyways.

2022-08-22 11:29 UTC, koebi commented on openrouteservice/src/main/resources/resources/locales/ors_de-DE.resources
> -			"7": "siebente",
Wenn wir hier schon alles anfassen, könnte man da kurz ein "fünfte" und "siebte" draus machen^^

2022-08-22 11:29 UTC, koebi commented on openrouteservice/src/main/resources/resources/locales/ors_eo-EO.resources
> +          "name": "Alvenis ĉe la nomo {way_name}"
das "la nomo" irritiert mich hier etwas - google translate übersetzt
  "Angekommen am Namen {way_name}", ohne das "la nomo" übersetzt es  "Angekommen in {way_name}".
  Passt auch eher mit dem "left" da unten, obwohl mich da auch das "Alvenu ce" und "Alvenis ce la nomo" im vergleich left/right irritiert…

2022-08-22 11:29 UTC, koebi commented on openrouteservice/src/main/resources/resources/locales/ors_eo-EO.resources
> +            "name": "Eniru la trafikcirklon kaj prenu la elirejon {exit_number} sur {way_name}"
Bin verwirrt warum hier einmal rondon und einmal trafikcirklon verwendet wird.
GTranslate übersetzt rondon mit "rund" oder so und "trafikcirklon" mit "Kreisverkehr"…

2022-08-29 08:16 UTC, takb commented
Fixed German language file, also revised the Esperanto as much as I could with google translate...

2022-09-05 08:38 UTC, koebi commented
Given that we don't know anyone that speaks esperanto, I'd say it's definitely good enough for now.
Maybe we can contact the Baden-Württemberg Esperanto Association (https://esperanto-bw.de/pages/de/start.php) and ask them to review? It is, after all, 30 Lines, so for somebody fluent I don't think it should take more than half an hour?

2022-09-06 12:31 UTC, koebi approved these changes

2022-09-06 13:55 UTC, merged

2022-09-06 13:55 UTC, takb commented
Sure, go ahead. In the meanwhile I'll still merge this as is.