ci: Only trigger on v7.* PRs
GIScience/openrouteservice pull request #1522
Opened 2023-08-08 15:46 UTC by MichaelsJP

Co-authored-by: Jochen Haeussler <jochen.haeussler@heigit.org>
Co-authored-by: Takara Baumbach <takara.baumbach@heigit.org>### Pull Request Checklist

- [ ] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [ ] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [ ] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes # .

### Information about the changes
- Key functionality added:
- Reason for change:

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
-

### Required changes to ors config (if applicable)
-

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

2023-08-10 15:57 UTC, jhaeu requested changes
Excellent, much work! Just some small notes.

2023-08-10 15:57 UTC, jhaeu commented on .github/workflows/rpm-build.yml
> +        uses: MichaelsJP/ghaction-import-gpg@v1.0
should we move this to GIScience?

2023-08-10 15:57 UTC, jhaeu commented on .github/workflows/rpm-build.yml
> +          gpg -K
use long options for better readability?

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/test_rhel8_post_install_check.sh
> +if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
```suggestion
```

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/test_rhel8_pre_install_check.sh
> +if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
```suggestion
```

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/scripts/helper_functions.sh
> +    result=$(docker exec -u root "$CONTAINER_NAME" bash -c "grep -Fx '$line' $path_to_file")
please test if correct: grep -Fx '$line'

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/test_rhel8_post_install_check.sh
> +find_owned_content "/opt/openrouteservice/*" "root" "root" 0 || exit 1
```suggestion
```

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/test_rhel8_post_install_check.sh
> +find_owned_content "/opt/openrouteservice/*" "jboss" "jboss" 0 || exit 1
```suggestion
```

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/ors-war.spec
>  # Allow 660 read and write for folders and 644 files for the ors group
```suggestion
# Allow 770 for read and write for files for the ors group
```

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/ors-war.spec
> +# Set recursive 760 permissions for the /opt/openrouteservice folder so that the ${ors_group} can read and write to it
```suggestion
# Set recursive 770 permissions for the /opt/openrouteservice folder so that the ${ors_group} can read and write to it
```

2023-08-10 15:57 UTC, jhaeu commented on .rpm-packaging/ors-war.spec
>  # Uninstall routine if $1 is 0 but leave the opt folder
create test?

2023-08-11 08:26 UTC, MichaelsJP commented on .github/workflows/rpm-build.yml
> +        uses: MichaelsJP/ghaction-import-gpg@v1.0
We still can in the future. But GIScience is already full of repos. I'd say we leave it at my space for now.

2023-08-11 08:47 UTC, MichaelsJP commented on .rpm-packaging/scripts/helper_functions.sh
> +    result=$(docker exec -u root "$CONTAINER_NAME" bash -c "grep -Fx '$line' $path_to_file")
yes it its. the subshell is treating the single quotes differently. i added now escaped double quotes to make it clearer

2023-08-11 12:10 UTC, jhaeu requested changes

2023-08-11 12:10 UTC, jhaeu commented on .rpm-packaging/rhel8_post_uninstall_check.sh
> +find_owned_content "/opt/openrouteservice/*" "openrouteservice" "openrouteservice" 0 || exit 1
```suggestion
```

2023-08-11 12:43 UTC, jhaeu approved these changes
LGTM

2023-08-11 12:44 UTC, merged