Feat/config cleanup finalize
GIScience/openrouteservice pull request #1657
Opened 2024-01-30 10:34 UTC by takb

### Pull Request Checklist

- [ ] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [ ] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [ ] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes # .

### Information about the changes
- Key functionality added:
- Reason for change:

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
-

### Required changes to ors config (if applicable)
-

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

2024-01-30 11:12 UTC, sfendrich requested changes
A few minor issues.

2024-01-30 11:12 UTC, sfendrich commented on .github/utils/config_rewrite.sh
> +awk -i inplace '/#    profile_default:/{getline; if ($0 ~ /#      enabled:/) {print "    profile_default:"; print "      enabled: false"; next}} {print}' "$output_file"
Line 23 can be removed.

2024-01-30 11:12 UTC, sfendrich commented on .github/utils/config_rewrite.sh
> +for profile in car hgv bike-regular bike-mountain bike-road bike-electric walking hiking public-transport; do
Here, all profiles should be left untouched, except car-profile should be turned `enabled: true`.

2024-01-30 11:12 UTC, sfendrich commented on .github/utils/config_rewrite.sh
> +# Replace '#    source_file:' with '    source_file: "YOUR_FILE"'
Should we use heidelberg instead of "YOUR_FILE"?

2024-01-30 11:12 UTC, sfendrich commented on .github/utils/config_rewrite.sh
> +sed -i 's/#    source_file:/    source_file: "YOUR_FILE"/g' "$output_file"
This might be risky, if other options also include a field called `source_file

2024-01-30 11:12 UTC, sfendrich commented on ors-api/ors-config.yml
> +# For a full list of possible parameters see https://giscience.github.io/openrouteservice/, below are some examples.
This will be overwritten and should be placed in application.yml

2024-01-30 11:12 UTC, sfendrich commented on ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
> +        System.setProperty(ORS_CONFIG_LOCATION_PROPERTY, output);
A deferred log would be more elegant: https://stackoverflow.com/questions/42839798/how-to-log-errors-in-a-environmentpostprocessor-execution

2024-01-30 11:12 UTC, sfendrich commented on ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
> +        LOGGER.info("");
The following is related to the deferred log ...

2024-01-30 13:43 UTC, takb commented on ors-api/ors-config.yml
> +# For a full list of possible parameters see https://giscience.github.io/openrouteservice/, below are some examples.
done.

2024-01-30 13:58 UTC, MichaelsJP commented on .github/utils/config_rewrite.sh
> +sed -i 's/#    source_file:/    source_file: "YOUR_FILE"/g' "$output_file"
I moved the source_file parameter directly under engine: so the script can parse the two together. Makes the possibility of namespace clashes less likely.

2024-01-30 13:59 UTC, MichaelsJP commented on .github/utils/config_rewrite.sh
> +# Replace '#    source_file:' with '    source_file: "YOUR_FILE"'
It now has the default Heidelberg pbf with the path from the root folder of the repo. It allows us to immediately  start ors with spring without any additional configuration.

2024-01-30 13:59 UTC, MichaelsJP commented on .github/utils/config_rewrite.sh
> +for profile in car hgv bike-regular bike-mountain bike-road bike-electric walking hiking public-transport; do
Fixed

2024-01-30 14:00 UTC, MichaelsJP commented on .github/utils/config_rewrite.sh
> +awk -i inplace '/#    profile_default:/{getline; if ($0 ~ /#      enabled:/) {print "    profile_default:"; print "      enabled: false"; next}} {print}' "$output_file"
gone

2024-01-31 08:21 UTC, sfendrich approved these changes
LGTM! Thank you.

2024-01-31 11:38 UTC, merged