fix(isochrones): correct and unify edge splitting
GIScience/openrouteservice pull request #1708
Opened 2024-03-04 00:14 UTC by aoles

### Pull Request Checklist

- [ ] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [ ] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [ ] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

### Information about the changes
- Key functionality added: Split edges based on difference in coordinates rather than their actual distance in meters, and use the same splitting length across isochrone builders
- Reason for change: Distance-based splitting proved to be unreliable, while different defaults across the builders introduced additional differences in the generated geometries. 

[config]: https://GIScience.github.io/openrouteservice/run-instance/configuration/
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

2024-03-04 11:22 UTC, sfendrich commented
Could you please elaborate on how this change affects isolines across the globe? Using geo-coordinates means measuring in degrees. The distance between coordinates varies a lot depending on the location and the used coordinate system. Imagine you would invent a coordinate system having its north pole in Berlin. would the isolines still have the same shape?

2024-03-04 12:19 UTC, aoles commented
Thanks @sfendrich, that's a fair point! What this PR tries to achieve is to perform edge splitting in the same coordinate system in which the concave hull is also being computed. The concave hull algorithm is parameterized by the target maximum edge length. Edge splitting makes sure that edge segments which are input to the concave hull algorithm do not exceed this limit.  This PR does not make any change to the concave hull part which actually computes the isochrone polygons. This part has alwas been done in the geocoordinate domain. Having said this, I agree that the generated shape is influenced by the location.

2024-03-05 08:31 UTC, sfendrich commented
So, if I build the same town two times, once in Alaska and once in Cameroon, the isochrones would differ in their shape? This sounds undesirable.

2024-03-05 09:46 UTC, aoles commented
While the above is true, this is also how it has always been like. Let me stress this again: this PR does not change how the isochrones are build in general. It just makes adjustments to the logic how the edges are split, and the splitting is there only to facilitate correct results from computing the concave hull.

Having said this, I don't think this discussion should be continued here. If you are not satisfied with the current solution of generating isochrone geometries you are welcome to open an issue. Cheers!

2024-03-05 10:03 UTC, rtroilo commented
> While the above is true, this is also how it has always been like. Let me stress this again: this PR does not change how the isochrones are build in general. It just makes adjustments to the logic how the edges are split, and the splitting is there only to facilitate correct results from computing the concave hull.
> 
> Having said this, I don't think this discussion should be continued here. If you are not satisfied with the current solution of generating isochrone geometries you are welcome to open an issue. Cheers!

But I think this could have a very easy fix, just make the smoothing-factor depending an the latitude of the center. What do you think?

2024-03-05 10:14 UTC, aoles commented
@rtroilo thanks for chiming in. I've thought about this too, however, the further apart you move from the equator the higher  the discrepancy between the length in meters of one latitudinal and one longitudinal degrees. The algorithm which computes the concave hull is parametrized only with one length and does not differentiate between XY directions. So effectively you still have the same issue, or do I miss something? 🤔

2024-03-05 11:26 UTC, sfendrich requested changes
Just two minor comments.

2024-03-05 11:26 UTC, sfendrich commented on ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
> +    private static final double MAX_SEGMENT_LENGTH = 0.18;// corresponds to 20000 m
What is the measurement unit?

2024-03-05 11:26 UTC, sfendrich commented on ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
> +        double normLength = Math.sqrt((dx * dx) + (dy * dy));
Why can we use cartesian norm in a non-cartesian coordinate system?

2024-03-05 11:35 UTC, sfendrich commented
O.K. So it seems there is something fundamentally wrong with isochrones which is independent of this PR, right?

Here is a new issue to continue the discussion: https://github.com/GIScience/openrouteservice/issues/1711

2024-03-05 11:46 UTC, aoles commented on ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
> +    private static final double MAX_SEGMENT_LENGTH = 0.18;// corresponds to 20000 m
Degrees.

2024-03-05 12:03 UTC, aoles commented on ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
> +        double normLength = Math.sqrt((dx * dx) + (dy * dy));
This is based on the fact that the rest of polygon processing, in particular the concave hull algorithm, assumes cartesian coordinates. I believe for smaller distances such approximation is legitimate. In fact, this is not the only place such norm is being used. Similar computations are being performed when adding buffer points,

https://github.com/GIScience/openrouteservice/blob/a890ad2230e8594b0000a35e687683641ef5c5ba/ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java#L78-L82

 and in the contour preprocessing part.

https://github.com/GIScience/openrouteservice/blob/a890ad2230e8594b0000a35e687683641ef5c5ba/ors-engine/src/main/java/org/heigit/ors/fastisochrones/Contour.java#L385-L388

2024-03-05 12:07 UTC, sfendrich commented on ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
> +    private static final double MAX_SEGMENT_LENGTH = 0.18;// corresponds to 20000 m
Then I suggest renaming it to `MAX_SEGMENT_ANGLE`.

2024-03-06 11:25 UTC, sfendrich approved these changes

2024-03-07 10:57 UTC, sfendrich commented on ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
> +    private static final double MAX_SEGMENT_LENGTH = 0.18;// corresponds to 20000 m
I've renamed it.

2024-03-07 11:14 UTC, aoles commented on ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
> +    private static final double MAX_SEGMENT_LENGTH = 0.18;// corresponds to 20000 m
Thank you for going forward and let me apologize for not responding to you earlier, I was busy with other stuff :innocent:

2024-03-07 17:14 UTC, MichaelsJP commented
@aoles Can we merge this?

2024-03-07 17:51 UTC, merged