docs: complete config and grc docu
GIScience/openrouteservice pull request #1898
Opened 2024-11-15 11:52 UTC by jhaeu

### Pull Request Checklist

- [ ] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [ ] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [ ] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes # .

### Information about the changes
- Key functionality added:
- Reason for change:

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
-

### Required changes to ors config (if applicable)
-

[config]: https://GIScience.github.io/openrouteservice/run-instance/configuration/
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

2024-11-21 14:46 UTC, MichaelsJP requested changes
Just a couple of things.

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/configuration-properties.md
> +# Configuration Properties
Everything until `Minimal Configuration` is quite interesting and general config content. This could imo directly fit in run-instance/configuration/.

This file could then just be called `minimal config`.

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/configuration-properties.md
> +  regarding [profiles](engine/profiles/) run on the instance.
```suggestion
  regarding [profiles](engine/profiles) run on the instance.
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/configuration-properties.md
> +see [How to set Properties](how-to-set-properties.md)
I extended the section. Please review.

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +The configuration or openrouteservice can be specified in different notations.
```suggestion
The configuration of openrouteservice can be specified in different notations.
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +  has been **deprecated** and will be eventually removed. Therefore, we strongly discourage you from using it. If you
```suggestion
  has been **deprecated** and removed in ORS version 9. Therefore, we strongly discourage you from using it. If you
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +see [Configuration Properties](/run-instance/configuration/configuration-properties.md#minimal-configuration).
```suggestion
see [Configuration Properties](configuration-properties.md#minimal-configuration).
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +For more details see [profiles](/run-instance/configuration/engine/profiles/index.md).
```suggestion
For more details see [profiles](engine/profiles/index.md).
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +### Configuration defaults output
Is this feature tested?

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +e.g. in [docker compose files](/run-instance/running-with-docker#set-openrouteservice-properties-in-docker-compose-yml)
```suggestion
e.g. in [docker compose files](../running-with-docker#set-openrouteservice-properties-in-docker-composeyml),
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +[env files](/run-instance/running-with-docker#set-openrouteservice-properties-in-an-environment-file)
```suggestoin
[env files](../running-with-docker#set-openrouteservice-properties-in-an-environment-file)
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +or in `setenv.sh` files in [tomcat setups](/run-instance/running-war#configure).
```suggestion
or in `setenv.sh` files in [tomcat setups](../running-war#configure).
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +* Internal defaults
```suggestion
If properties are set in several configuration sources,
the priority is as follows. 1 (highest priority) to 5 (lowest):

1. Spring Run Arguments override
2. JVM Program Arguments override
3. Environment Variables override
4. Properties defined in the single used config file override
5. Internal defaults
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +A openrouteservice running in a container works in the same way as described in this chapter.
```suggestion
An openrouteservice instance running in a container works in the same way as described in this chapter.
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +with a separat file system (different paths) and individual environmen variables.
```suggestion
with a separate file system (different paths) and individual environment variables.
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +when specifying the config file in the parameter ors_config_location.
```suggestion
when specifying the config file in the parameter `ors_config_location`.
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +in contrast to applications running directly on the host sytem,
```suggestions
in contrast to applications running directly on the host system,
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +[Running with Docker](/run-instance/running-with-docker#configure) describes in detail,
```suggestion
[Running with Docker](../running-with-docker#configure) describes in detail,
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +the ([Graph Repo Client](/technical-details/graph-repo-client/index.md)).
```suggestion
the ([Graph Repo Client](../../technical-details/graph-repo-client/index.md)). 
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/index.md
> +In Chapter [How to set Properties](/run-instance/configuration/how-to-set-properties.md)
```suggestion
In Chapter [How to set Properties](/run-instance/configuration/how-to-set-properties.md)
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/index.md
> +a [minimal configuration example](/run-instance/configuration/configuration-properties.md#minimal-configuration).
```suggestion
a [minimal configuration example](configuration-properties.md#minimal-configuration).
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/index.md
> +Chapter [Configuration Properties](/run-instance/configuration/configuration-properties.md)
```suggestion
Chapter [Configuration Properties](configuration-properties.md)
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/technical-details/graph-repo-client/index.md
> +configuring [ors.engine.graphs_data_acces](/run-instance/configuration/engine/index.md#orsengine)=`MMAP`,
```suggestion
configuring [ors.engine.graphs_data_acces](../../run-instance/configuration/engine/index.md#orsengine)=`MMAP`,
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/engine/profiles/index.md
> +[internal defaults](/run-instance/configuration/how-to-set-properties.md#internal-defaults).
```suggestion
[internal defaults](../../how-to-set-properties.md#internal-defaults).
```

2024-11-21 14:46 UTC, MichaelsJP commented on docs/run-instance/configuration/engine/profiles/index.md
> +See [Defining Defaults for all Routing Profiles](/run-instance/configuration/how-to-set-properties.md#defining-defaults-for-all-routing-profiles)
```suggestion
See [Defining Defaults for all Routing Profiles](../../how-to-set-properties.md#defining-defaults-for-all-routing-profiles)
```

2024-11-21 15:09 UTC, jhaeu commented on docs/run-instance/configuration/configuration-properties.md
> +# Configuration Properties
OK, will re-structure it

2024-11-21 15:15 UTC, jhaeu commented on docs/run-instance/configuration/configuration-properties.md
> +see [How to set Properties](how-to-set-properties.md)
OK, let's keep it. But one of my motivations were exactly to remove this kind of de-focusing and redundancy :D The link targets to a place where exactly this is explained.

2024-11-21 15:51 UTC, jhaeu commented on docs/run-instance/configuration/engine/profiles/index.md
> +[internal defaults](/run-instance/configuration/how-to-set-properties.md#internal-defaults).
i would like to avoid up-downwards relative links - absolute links are way better readable

2024-11-21 15:56 UTC, jhaeu commented on docs/run-instance/configuration/how-to-set-properties.md
> +### Configuration defaults output
probably not...

2024-11-21 16:03 UTC, jhaeu commented on docs/run-instance/configuration/how-to-set-properties.md
> +e.g. in [docker compose files](/run-instance/running-with-docker#set-openrouteservice-properties-in-docker-compose-yml)
you suggested change breaks the link

2024-11-21 16:04 UTC, jhaeu commented on docs/run-instance/configuration/how-to-set-properties.md
> +[env files](/run-instance/running-with-docker#set-openrouteservice-properties-in-an-environment-file)
don't like relative upwards links

2024-11-21 16:04 UTC, jhaeu commented on docs/run-instance/configuration/how-to-set-properties.md
> +or in `setenv.sh` files in [tomcat setups](/run-instance/running-war#configure).
see above

2024-11-21 16:08 UTC, jhaeu commented on docs/run-instance/configuration/how-to-set-properties.md
> +[Running with Docker](/run-instance/running-with-docker#configure) describes in detail,
see above

2024-11-21 18:55 UTC, MichaelsJP commented on docs/run-instance/configuration/engine/profiles/index.md
> +[internal defaults](/run-instance/configuration/how-to-set-properties.md#internal-defaults).
Sure. But the links would still be wrong. 
`/run-instance/configuration` -> `/docs/run-instance/configuration`. This is true to all other links that were part of the review.

2024-11-21 18:56 UTC, MichaelsJP commented
One last thing. The TOC in `getting-started.md` needs to be updated with the new pages.

2024-11-22 10:55 UTC, MichaelsJP requested changes
Minor typo

2024-11-22 10:55 UTC, MichaelsJP commented on docs/run-instance/configuration/how-to-set-properties.md
> +in contrast to applications running directly on the host sytem,
```suggestion
in contrast to applications running directly on the host system,
```

2024-11-22 10:57 UTC, MichaelsJP approved these changes
LGTM

2024-11-22 11:09 UTC, merged