feature-#349 list traversal countries
GIScience/openrouteservice pull request #514
Opened 2019-05-21 19:59 UTC by MichaelsJP

### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the development branch into my feature branch and all conflicts have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [x] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [x] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #349  .

### Information about the changes
- Key functionality added: Return the countries the route traverses under route extras.
- Reason for change: It's nice to know ;).

### Examples and reasons for differences between live ORS routes and those generated from this pull request
-

### Required changes to app.config (if applicable)
-

2019-05-22 13:13 UTC, rabidllama requested changes
Have you also run this on a larger dataset that crosses real life borders to make sure that query times aren't heavily affected? (they shouldn't be but worth just checking)

2019-05-22 13:13 UTC, rabidllama commented on openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/reader/borders/CountryBordersReader.java
> +    public static CountryBordersPolygon[] getCountriesByPointList(PointList pointList) {
This method doesn't make much sense - you are creating three arrays of the polygons, but only ever returning the empty one...

2019-05-22 13:13 UTC, rabidllama commented on openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/BordersGraphStorage.java
> +		short border;
Why are we creating the variables and then instantiating them in later calls rather than doing it in one line?

2019-05-22 13:13 UTC, rabidllama commented on openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/builders/BordersGraphStorageBuilder.java
> +                     _storage.setEdgeValue(edge.getEdge(), type, start, end);
We don't need to call this once in each part of the if - it can be done just once after the if as all the if does is set the type value.

You can even remove the else statement by setting the type value to be the NO_BORDER when you create it at line 154.

2019-05-22 13:13 UTC, rabidllama commented on openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/builders/BordersGraphStorageBuilder.java
> +//        if (countries.size() > 2){
Remove commented code

2019-05-24 08:56 UTC, MichaelsJP commented on openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/reader/borders/CountryBordersReader.java
> +    public static CountryBordersPolygon[] getCountriesByPointList(PointList pointList) {
Yep. Good find. Was a leftover.

2019-05-24 09:26 UTC, MichaelsJP commented on openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/BordersGraphStorage.java
> +		short border;
As far as I understood, primitives like short always derfault to zero if not initialized with something else. So no need to.

2019-05-24 09:38 UTC, MichaelsJP commented on openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/BordersGraphStorage.java
> +		short border;
Absolutely right. I intentionally kept it the way it was done before.

2019-05-24 09:43 UTC, MichaelsJP commented
> Have you also run this on a larger dataset that crosses real life borders to make sure that query times aren't heavily affected? (they shouldn't be but worth just checking)

I'm currently running Ireland and northern Ireland.

2019-05-24 15:08 UTC, MichaelsJP commented
I compared the performance for the branches dev and feature and there are no differences. It's ready to be merged.

2019-05-28 13:41 UTC, closed without merging