fix algo selection for alternative routes with CORE and no LM
GIScience/openrouteservice pull request #635
Opened 2019-12-12 15:35 UTC by takb

Fixes issues with AlternativeRoutes in case the profile setup has Core enabled and no LM. Also adds a test for AR requests with restriction params.

2019-12-13 12:57 UTC, aoles commented
TY for the fix! For a given weighting which has both CH and ALT enabled I still observe fallback to A* with beeline rather than ALT when no route filters are enabled. Can you confirm?

2019-12-13 13:31 UTC, aoles requested changes
For a given weighting which has both CH and ALT enabled for a route without any filters switched on I still observe `AlternativeRoute` to use A* with the beeline rather than the landmarks approximator. This doesn't happen when no CH is available just ALT.

2019-12-16 07:40 UTC, sfendrich approved these changes

2019-12-16 11:07 UTC, takb commented
The flag setting code in RoutingProfile is a real mess. Added explicit setting of the LM flag in order to not disrupt the logic for other routing methods.

2020-01-08 10:11 UTC, closed without merging